/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.MenuControlador;
import Dao.CultivoDAO;
import Dao.TrabajadorDAO;
import Dao.impl.CultivoDAOImpl;
import Dao.impl.TrabajadorDAOImpl;
import Modelo.Usuario;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import servicio.CultivoServicio;
import servicio.TrabajadorServicio;

/**
 *
 * @author ilope
 */
public class FrmPrincipal extends javax.swing.JFrame {
   private final Usuario usuarioLogueado;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal(Usuario usuarioLogueado) {
         this.usuarioLogueado = usuarioLogueado;
        initComponents();
        configurarSegunRol();

        // Crear DAOs
        CultivoDAO cultivoDAO = new CultivoDAOImpl();
        TrabajadorDAO trabajadorDAO = new TrabajadorDAOImpl();

        // Crear servicios
        CultivoServicio cultivoServicio = new CultivoServicio(cultivoDAO);
        TrabajadorServicio trabajadorServicio = new TrabajadorServicio(trabajadorDAO);

        //Pasarlos al controlador del menú
        new MenuControlador(usuarioLogueado, this, cultivoServicio, trabajadorServicio);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCultivos = new javax.swing.JButton();
        btnAlmacen = new javax.swing.JButton();
        btnProduccion = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnTrabajadores = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 67, 50));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        btnCultivos.setBackground(new java.awt.Color(35, 35, 35));
        btnCultivos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCultivos.setForeground(new java.awt.Color(255, 255, 255));
        btnCultivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/planta.png"))); // NOI18N
        btnCultivos.setText("Cultivos");

        btnAlmacen.setBackground(new java.awt.Color(35, 35, 35));
        btnAlmacen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAlmacen.setForeground(new java.awt.Color(255, 255, 255));
        btnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/almacen.png"))); // NOI18N
        btnAlmacen.setText("Almacen");
        btnAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenActionPerformed(evt);
            }
        });

        btnProduccion.setBackground(new java.awt.Color(35, 35, 35));
        btnProduccion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnProduccion.setForeground(new java.awt.Color(255, 255, 255));
        btnProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/horticultura.png"))); // NOI18N
        btnProduccion.setText("Produccion");

        btnUsuarios.setBackground(new java.awt.Color(35, 35, 35));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/team_123415.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");

        btnTrabajadores.setBackground(new java.awt.Color(35, 35, 35));
        btnTrabajadores.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTrabajadores.setForeground(new java.awt.Color(255, 255, 255));
        btnTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agricultura.png"))); // NOI18N
        btnTrabajadores.setText("Trabajadores");
        btnTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajadoresActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(35, 35, 35));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion-de-usuario.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCultivos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTrabajadores)
                        .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnCultivos)
                .addGap(18, 18, 18)
                .addComponent(btnAlmacen)
                .addGap(18, 18, 18)
                .addComponent(btnProduccion)
                .addGap(18, 18, 18)
                .addComponent(btnTrabajadores)
                .addGap(18, 18, 18)
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(129, 129, 129))
        );

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(27, 67, 50));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/evolucion.png"))); // NOI18N
        jLabel1.setText("Sistema Agricola");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrabajadoresActionPerformed

    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlmacenActionPerformed
    private void configurarSegunRol() {
        if (usuarioLogueado.getRol() != Modelo.EnuRol.ADMIN) {
            btnTrabajadores.setEnabled(false);
            btnUsuarios.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlmacen;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCultivos;
    private javax.swing.JButton btnProduccion;
    private javax.swing.JButton btnTrabajadores;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAlmacen() {
        return btnAlmacen;
    }

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public JButton getBtnCultivos() {
        return btnCultivos;
    }

    public JButton getBtnTrabajadores() {
        return btnTrabajadores;
    }

    public JButton getBtnUsuarios() {
        return btnUsuarios;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public JButton getBtnProduccion() {
        return btnProduccion;
    }

   

}
